### ISSUE TITLE
Purpose of `package.json` file and its content?

### ISSUE THREAD

**Issue by xezo360hye** [K4zoku/nowm#7]
I am currently doing some work with this project and I am curious if `package.json` file is still needed and valid. It is very old and seems kinda outdated (eg. `nowmc` file is mentioned but it is no longer here). Is it ok to remove the `package.json`? I think Makefile is more than enough and if not I can just copy-and-edit its content to `install.sh` and `uninstall.sh` shell scripts

**Comment by xezo360hye** [comment]
By the way, one more question. Is NoWM strictly for POSIX sh or can Bash'es extended syntax (for instance, `[[` over `[` is recommended) be used?

**Comment by K4zoku** [comment]
> Is it ok to remove the package.json?
No, `package.json` is using for bpkg packaging

> It is very old and seems kinda outdated (eg. nowmc file is mentioned but it is no longer here)
I just updated in commit [76a5557](https://github.com/K4zoku/nowm/commit/76a55578415b9a2b72d2813221705c6f2df9fe48)

> Is NoWM strictly for POSIX sh or can Bash'es extended syntax (for instance, [[ over [ is recommended) be used?
Strictly POSIX

**Comment by xezo360hye** [comment]
One more thing (I hope you will see this). Why is there `select_focus` function? Imo it is totally useless with `pointer_focus` available as it just duplicates its functionality but with mouse pressing (which is just hotkeys config that is even in examples). Can/should it be deleted?

Sorry for so many questions, I just don't want to mess badly with someone's code

**Comment by xezo360hye** [comment]
Also idk what's the problem but `nowm quit` absolutely doesn't work. I mean, it does NOTHING. Manual `xdotool getwindowfocus windowquit` has the same result - window still alive, no errors, no questions, nothing. Can you please explain what it does and when it is needed?

**Comment by K4zoku** [comment]
Please consider create new issue instead of asking here

btw `pointer_focus` not work on some window (e.g sublime-text), that why I added `select_focus`

> Also idk what's the problem but `nowm quit` absolutely doesn't work

Let's move to new issue
